### PR TITLE
Update components architecture diagram

### PR DESCRIPTION
**Pull request by jordan-palacios**
First version of the updated components architecture diagram.

I have stripped most of the notes and added relations.

### CODE REVIEW

**Comment by bmagyar** [comment]
Small changes I suggest: 

`claim interfaces from`  I'd change this to reflect the mechanism we have now where the controllers report to CM/RM what they require and they are *assigned* interfaces by CM/RM.

I'd also try to incorporate the Systems mechanism where they create their resource interfaces and *export* them to the RM

**Review by bmagyar — CHANGES_REQUESTED** [review]
Small changes I suggest:

claim interfaces from I'd change this to reflect the mechanism we have now where the controllers report to CM/RM what they require and they are assigned interfaces by CM/RM.

I'd also try to incorporate the Systems mechanism where they create their resource interfaces and export them to the RM

**Comment by gavanderhoorn** [comment]
> claim interfaces from I'd change this to reflect the mechanism we have now where the controllers report to CM/RM what they require and they are assigned interfaces by CM/RM.

Would *request* for the controllers and *grant* for the CM/RM be good descriptions?

Assignment sounds like controllers could be assigned whatever and just have to deal with it.

**Comment by jordan-palacios** [comment]
> I'd also try to incorporate the Systems mechanism where they create their resource interfaces and export them to the RM

I don't quite get this one. You mean the fact that System's may export interfaces from multiple Actuators/Sensors?

**Comment by bmagyar** [comment]
> Would request for the controllers and grant for the CM/RM be good descriptions?
> Assignment sounds like controllers could be assigned whatever and just have to deal with it.
Great suggestion, although `assign` is basically what's happening now, we expect the controller manager is right. We aim to add some checks into the same function in ControllerInterface to do the verification

**Comment by bmagyar** [comment]
> @bmagyar I don't quite get this one. You mean the fact that System's may export interfaces from multiple Actuators/Sensors?

No, that's not what I meant. I meant that a System is responsible for transferring ownership of it's resources on `export_interfaces`

**Comment by jordan-palacios** [comment]
@bmagyar @gavanderhoorn Tried to add your suggestions. What do you guys think?

I'm also thinking on removing any mention to vectors or maps and try to let the design speak for itself.

**Comment by bmagyar** [comment]
This is really spot on!! Indeed, the C++ details are a little distracting, I agree with the idea of removing map and vectors.

I was tempted to ask to involve some controller management logic, etc but that'd overload this figure. For the ROS2 docs page we could create an alternative of this where we show starting/stopping components and controllers and how that interaction works + controller manager services.

**Review by bmagyar — APPROVED** [review]

**Comment by jordan-palacios** [comment]
@bmagyar Final version.

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
Thanks for the update and thumbs up for adding the xml too

**Comment by destogl** [comment]
@jordan-palacios this looks very good!

P.S. sorry for not getting to this earlier...

**Pull request merged**
