### PR TITLE
Start design of boilerplate repository/package

### PR DESCRIPTION
**Pull request by destogl**
Here is an initial commit of desing proposal for `ros2_control_boilerplate` repository.

### CODE REVIEW

**Comment by destogl** [comment]
Meeting Wednesday, 22th April: rename the package to `ros2_control_demo`

**Comment by destogl** [comment]
@bmagyar: could you create a new repository `ros2_control_demo` and give me write rights there? Or add me to the organization?

**Comment by bmagyar** [comment]
Will do it right away. You already have permissions for the project itself

**Comment by bmagyar** [comment]
https://github.com/ros-controls/ros2_control_demos

**Pull request merged**
